### PR TITLE
Adding prettier & expo eslint config

### PR DESCRIPTION
**Pull request by yoeven**
Hi @lane-c-wagner, I've added prettier support and [expo eslint config](https://github.com/expo/expo/tree/master/packages/eslint-config-universe) so there will be consistency in styling for future PRs and reduce unnecessary large `git diff`

### CODE REVIEW

**Comment by lane-c-wagner** [comment]
Sorry, I don't see any styling changes that make this change seem "worth it". We already have some eslinting that seems to be working well? What specifically are you trying to address with styling?

**Comment by yoeven** [comment]
Basically issues as we faced in the previous PR, where styling such as `''` was changed to `""` due to our difference in IDE settings, etc. So by setting a standard of formating such with prettier, we wouldn't need to manually track styling changes. It's also possible to set test which checks on styling using the prettier config to reject PRs that don't follow the standards automatically in the future.

**Comment by lane-c-wagner** [comment]
I think the problem was that styling we being ignored, not that it doesn't exist... I already have eslint rules setup, so I don't think we need a second dependency (prettier): https://github.com/lane-c-wagner/react-native-expo-cached-image/blob/master/.eslintrc.json

If there are missing rules we can add them but I'd rather keep it simple

**Comment by yoeven** [comment]
Yup, I got it. I just thought prettier would complement eslint by automatically reformating the codes based on your eslint rules. I'll close the PR if there's nothing else?

**Pull request closed without merging**
